apiVersion: v1 
kind: Pod 
metadata: 
  name: busybox
  namespace: kafka
  labels: 
    app: busybox 
spec: 
  containers: 
    - name: busybox
      image: yauritux/busybox-curl
#      image: busybox 
      command: 
        - tail 
        - "-f"
        - "/dev/null"
      imagePullPolicy: IfNotPresent 
  restartPolicy: Always
