apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  labels:
   volume-task: elasticsearch
spec:
  capacity:
    storage: {{ storage }}Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: {{ server }}
    path: {{ path }}
