# NFS FS exports should be "no_root_squash"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-workspace
  namespace: infra
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-maven-repo
  namespace: infra
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
