kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mwportal-db-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
