kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mwportal-db-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
