kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: logstash-tomcat
  namespace: logcenter
spec:
  template:
    metadata:
      labels:
        app: logstash-for-accesslog
    spec:
      containers:
      - name: logstash
        ports:
          - containerPort: 5044
            name: filebeat
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.1.0
        volumeMounts:
        - name: logstash-tomcat           # for default logstash.yml
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-tomcat-pipeline  # for default 
          mountPath: /usr/share/logstash/pipeline/pipeline-tomcat.conf
          subPath: pipeline-tomcat.conf
        - name: logstash-pvc-tomcat
          mountPath: /applog
        command:
        - logstash
        - -f
        - /usr/share/logstash/pipeline/pipeline-tomcat.conf
        # - --config.reload.automatic
        # - /usr/share/logstash/pipeline/mtwd-accesslog-parse.conf
      volumes:
      - name: logstash-tomcat
        configMap:
          name: logstash-tomcat
          defaultMode: 420
      - name: logstash-tomcat-pipeline
        configMap:
          name: logstash-tomcat-pipeline
          defaultMode: 420
      - name: logstash-pvc-tomcat
        persistentVolumeClaim:
          claimName: logstash-pvc-tomcat
      nodeSelector:
        node-role.kubernetes.io/management: "true"
