---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gitlab-ce
  namespace: infra
spec:
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:12.1.0-ce.0
        securityContext:
          runAsUser: 0
        ports:
          - containerPort: 22
            name: ssh
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab
        - name: log
          mountPath: /var/log/gitlab
        - name: data
          mountPath: /var/opt/gitlab
        - name: gitlab-rb
          mountPath: /etc/gitlab/gitlab.rb # /etc/gitlab/gitlab -> gitlab.rb
          subPath: gitlab.rb
          # mountPath: /etc/gitlab/gitlab.rb.edit  # /etc/gitlab/gitlab.rb.edit/gitlab.rb -> gitlab.rb
          # mountPath: /etc/gitlab/1  # /etc/gitlab/1 -> gitlab.rb
          # subPath: gitlab.rb
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: gitlab-ce-config
      - name: log
        persistentVolumeClaim:
          claimName: gitlab-ce-log
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-ce-data
      - name: gitlab-rb
        configMap:
          name: gitlab-ce
          defaultMode: 444
---
