---
- name: kubeadm aggregate all SANs
  set_fact:
    apiserver_sans: >-
      kubernetes
      kubernetes.default
      kubernetes.default.svc
      kubernetes.default.svc.cluster
      kubernetes.default.svc.cluster.local
      {{ master_ip }}
      {{ ' '.join(groups['master']) }}
      {%- for host in groups['master'] %}
      {{ hostvars[host]['ansible_host'] }}
      {%- endfor %}
      {{ master_external_ip }}
      localhost
      127.0.0.1
      10.254.0.1
      10.96.0.1
  tags: facts
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['backup-master'] 

- name: default addon directory
  file: path={{ kube_addon_dir }} state=directory
  register: default_addon_dir
  when: 
    - inventory_hostname in groups['master'] or inventory_hostname in groups['master-cluster'] or inventory_hostname in groups['backup-master']
  ignore_errors: True

- name: Kubeadm init on master node (weave)
  shell: "kubeadm init --ignore-preflight-errors=all"
  register: kubeadm_init
  when:
    - network_cni == 'weave'
    - inventory_hostname in groups['master']
  ignore_errors: True

- set_fact: adminit="{{kubeadm_init}}"
  when: kubeadm_init.changed

- name: make direcotry (.kube)
  file: path=/root/.kube state=directory
  register: kubeconfig_addon_dir
  ignore_errors: True
  when: inventory_hostname in groups['master']

- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
  when: inventory_hostname in groups['master']

- set_fact: adminit="{{kubeadm_init}}"
  when: kubeadm_init.changed

############# Selected ###########
- name: Get the token id from the master initialization ( k8s 1.15 )
  shell: "echo '{{ adminit.stdout }}' | tail -n1 | awk '{print $5}'"
  register: kubeadm_token
  when:
    - kubernetes_version | search('1.14') or kubernetes_version | search('1.15')
    - inventory_hostname in groups['master']

- name: set var fact
  set_fact:
    token: "{{kubeadm_token}}"
  when: kubeadm_token.changed

- name: print output of kubeadm_token
  vars:
    join_token: "{{ token.stdout_lines }}"
  debug: msg="{{ token.stdout_lines }}"
  when: inventory_hostname in groups['master']
  tags:
    - output
############# Selected ###########

############# Selected ###########
- name: Get the IP and port from the master initialization ( k8s 1.15 )
  shell: "echo '{{ adminit.stdout }}' | tail -n1 | awk '{print $3}'"
  register: kubeadm_master_ip_port
  when:
    - kubernetes_version | search('1.14') or kubernetes_version | search('1.15')
    - inventory_hostname in groups['master']

- name: set var fact
  set_fact:
    ip_port: "{{kubeadm_master_ip_port}}"
  when: kubeadm_master_ip_port.changed

- name: print output of kubeadm_master_ip_port
  vars:
    join_ip_port: "{{ ip_port.stdout_lines }}"
  debug: msg="{{ ip_port.stdout_lines }}"
  when: inventory_hostname in groups['master']
  tags:
    - output
############# Selected ###########

############# Print vars ###########
- name: Custom - print output of join_token / join_ip_port for Master
  vars:
    print_vars: "{{ token.stdout_lines }} {{ ip_port.stdout_lines }}"
  debug: var=print_vars
  when: inventory_hostname in groups['master']

- name: Custom - print output of join_token / join_ip_port for Minions
  vars:
    print_vars: "{{ hostvars[groups['master'][0]].token.stdout }} {{ hostvars[groups['master'][0]].ip_port.stdout }}"
  debug: var=print_vars
  when: inventory_hostname in groups['minions']

- name: Custom - print join command for Minions
  vars:
#    print_cmd: "kubeadm join {{ ip_port }} --token {{ token }} --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification"
#    print_cmd: "kubeadm join {{ ip_port.stdout_lines }} --token {{ token.stdout_lines }} --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification"
     print_cmd: "kubeadm join {{ hostvars[groups['master'][0]].ip_port.stdout }} --token {{ hostvars[groups['master'][0]].token.stdout }} --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification"
  debug: var=print_cmd
  when: inventory_hostname in groups['minions']
############# Print vars ###########

- name: Join nodes with master
  shell: >
    kubeadm join {{ hostvars[groups['master'][0]].ip_port.stdout }} --token {{ hostvars[groups['master'][0]].token.stdout }} --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification
  register: kubeadm_join_command
  tags:
    - output
  when:
    - inventory_hostname in groups['minions'] or inventory_hostname in groups['infra']

- name: Template config.yaml
  template:
    src: config.yaml.j2
    dest: /var/lib/kubelet/config.yaml
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['minions'] or inventory_hostname in groups['infra']
    - kubernetes_version | search('1.14') or kubernetes_version | search('1.15')

- name: Template kubeadm-flags.env
  template:
    src: kubeadm-flags.env.j2
    dest: /var/lib/kubelet/kubeadm-flags.env
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['minions'] or inventory_hostname in groups['infra']
    - kubernetes_version | search('1.14') or kubernetes_version | search('1.15')
    
- name: Template kubelet
  template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet
  when:
    - inventory_hostname in groups['master'] or inventory_hostname in groups['minions'] or inventory_hostname in groups['infra']
    - kubernetes_version | search('1.14') or kubernetes_version | search('1.15')

- name: Reload changing kubelet
  command: systemctl daemon-reload

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - kubelet

- wait_for:
    host: 127.0.0.1
    port: "{{ kube_apiserver_port }}"
    delay: 10
  when: inventory_hostname in groups['master']

- name: Copy coredns_configmap.sh
  copy:
    src: coredns_configmap.sh
    dest: "{{ kube_addon_dir }}/coredns_configmap.sh"
  when: inventory_hostname in groups['master']

- name: "Mode 755 for coredns_configmap.sh"
  file:
    path: "{{ kube_addon_dir }}/coredns_configmap.sh"
    mode: 0755
  when: inventory_hostname in groups['master']

- name: Run coredns_configmap.sh
  shell: >
    /bin/sh -c "{{ kube_addon_dir }}/coredns_configmap.sh"
  when: inventory_hostname in groups['master']

