---
- name: stop kubelet
  service:
    name: kubelet
    state: stopped
  ignore_errors: True

- name: stop docker
  service:
    name: docker
    state: stopped
  ignore_errors: True

- name: stop nfs-server
  service:
    name: nfs-server
    state: stopped
  ignore_errors: True

- name: disable kubelet
  service:
    name: kubelet
    enabled: no
  ignore_errors: True

- name: disable docker
  service:
    name: docker
    enabled: no
  ignore_errors: True

- name: disable nfs-server
  service:
    name: nfs-server
    enabled: no
  ignore_errors: True
