apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafka
  namespace: infra
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kafka.mwportal.com   # Worked
    http:
      paths:
      - backend:
          serviceName: kafka
          servicePort: 9092
        path: /
