apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: infra
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      targetPort: 9092
      port: 9092        # ClusterPORT with ClusterIP
      nodePort: 31414
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  sessionAffinity: None
