---
apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes
  namespace: default
  resourceVersion: "9"
subsets:
- addresses:
  - ip: 192.0.0.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "8"
spec:
  clusterIP: 10.96.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: ClientIP
status:
  loadBalancer: {}