apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: accordion
  labels:
    k8s-app: registry
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: registry
  type: NodePort
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    nodePort: 30001
#  - name: registry-ui
#    port: 80
#    protocol: TCP
#    nodePort: 32001
