kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvc
  namespace: accordion
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume-task: registry
