# k label nodes vm-master1 node-role.kubernetes.io/master="true" --overwrite
# k label nodes vm-worker1 node-role.kubernetes.io/worker="true" --overwrite
# k label nodes vm-worker2 node-role.kubernetes.io/worker="true" --overwrite
---
- name: create node label - Master
  command: 'kubectl label nodes {{ inventory_hostname }} node-role.kubernetes.io/master=true --overwrite'
  delegate_to: "{{ groups['master'][0] }}"       # Only at group master
  when:
    - inventory_hostname in groups['master']
  ignore_errors: yes

- name: create node label - Worker
  command: 'kubectl label nodes {{ inventory_hostname }} node-role.kubernetes.io/worker=true --overwrite'
  delegate_to: "{{ groups['master'][0] }}"       # Only at group master
  when:
    - inventory_hostname in groups['minions']
  ignore_errors: yes

- name: create node label - Worker1 to mgt
  command: 'kubectl label nodes {{ inventory_hostname }} node-role.kubernetes.io/management=true --overwrite'
  delegate_to: "{{ groups['master'][0] }}"       # Only at group master
  when:
    - inventory_hostname in groups['managements']
  ignore_errors: yes

- name: show node label
  command: 'kubectl get node --show-labels'
  delegate_to: "{{ groups['master'][0] }}"       # Only at group master
  when:
    - inventory_hostname in groups['master']
  ignore_errors: yes

#- name: node taint
#  command: 'kubectl taint nodes {{ inventory_hostname }} kubernetes.io/hostname={{ inventory_hostname }}:NoSchedule'
#  command: 'kubectl taint nodes {{ inventory_hostname }} accordion-role=infra:NoSchedule'
#  command: 'kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/master=true:NoSchedule
#  delegate_to: "{{ groups['master'][0] }}"
#  when: inventory_hostname in groups['infra']
#  ignore_errors: yes

#- wait_for:
#    port: 6783
#    delay: 15
