apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport-2
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      targetPort: 9092
      port: 9092        # ClusterPORT with ClusterIP
      nodePort: 31092
  selector:
    app: kafka
    release: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
  sessionAffinity: None
