apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      targetPort: 9092
      port: 9092        # ClusterPORT with ClusterIP
      nodePort: 31414
  selector:
    app: kafka
    release: kafka
  sessionAffinity: None
